version: '3.7'

services:
  tgbot:
    build: ./
    restart: always
    command: bash entrypoint.sh
    env_file:
      - ./.env
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:13.1
    restart: always
    volumes:
      - tgbot_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5434:5432

volumes:
  tgbot_postgres_data: